Improvements to temperature panel resizing
ImperialCollegeLondon/FINESSE pull request #209
Opened 2023-04-20 15:33 UTC by dc2917

This PR includes some improvements to the resizing of panels on the right-hand side of the GUI, as well as an aesthetic improvement to the buttons which toggle plot visibility.

Upon resizing of the window, only the panel containing the temperature plot is now free to expand vertically. However, as this panel contains a `QGridLayout`, which contains widgets with different `QSizePolicy`s, a custom resize function is required to maximise the space taken up by the figure.

2023-04-21 09:09 UTC, alexdewar requested changes
This looks much nicer. Good work! I think we should probs also move the OPUS panel somewhere else (maybe into the gap in the lefthand layout?) and then the plot can be even larger and then it'll look great. That's a job for another PR though.

I've made one small suggestion, but other than that I'm happy with it. The only thing is that I'm a bit concerned that the custom resize function feels like a bit of a hack. It's entirely possible that that's the only way to do what we want, but I've requested a review from @dalonsoa anyway to see if he's got any better ideas.

2023-04-21 09:50 UTC, dc2917 commented
I've just found an issue with the resizing, so this needs a bit more work before reviews.

2023-04-21 10:17 UTC, dc2917 commented
> This looks much nicer. Good work! I think we should probs also move the OPUS panel somewhere else (maybe into the gap in the lefthand layout?) and then the plot can be even larger and then it'll look great. That's a job for another PR though.
> 
> I've made one small suggestion, but other than that I'm happy with it. The only thing is that I'm a bit concerned that the custom resize function feels like a bit of a hack. It's entirely possible that that's the only way to do what we want, but I've requested a review from @dalonsoa anyway to see if he's got any better ideas.

Yeah I completely agree that it feels like a hack. I was happy that I could at least set the figure position and size based on those of other widgets, which are decided by Qt.

I think the issue is that I set a minimum size for the figure. If I don't do this, then that panel is tiny by default - Qt seems to set its height to be the vertical distance between the top of the "Hot BB" button and the bottom of the "Cold BB" button. This itself, I think, is due to the size policies of the layouts. But we've seen what happens if we let Qt choose the size policies - the OPUS panel gets all the space. For this same reason, if I don't set the size policy of either the "Hot BB" and "Cold BB" buttons or the figure, the buttons get all the space. 

In short, it seems we do need to override some Qt behaviour. I'm sure there will be improvements to the way I've done this, but I think something of this sort is necessary.

2023-04-21 10:45 UTC, dc2917 commented on finesse/gui/main_window.py
> +
Even though we've made it so that each component can be run as a standalone GUI?

2023-04-21 10:53 UTC, alexdewar commented on finesse/gui/main_window.py
> +
Yeah. I think that was fine for testing, but I don't know that we really need that capability now that things are better integrated. There are so many moving parts now I suspect most of the components won't actually work standalone now anyway, especially seeing as we don't have tests for those bits.

2023-04-21 10:57 UTC, dc2917 commented on finesse/gui/main_window.py
> +
Makes sense!

2023-04-21 14:08 UTC, alexdewar approved these changes
Aside from a trivial merge conflict, I think this is good to go!

2023-04-25 12:04 UTC, dalonsoa commented
Starting to renew this. It looks good, but the process is not that robust. This is what I get after a couple of resizes (in MacOS):

<img width="814" alt="image" src="https://user-images.githubusercontent.com/6095790/234270506-f2529559-fb8d-49b8-82b1-a1f97cdbd21c.png">

I'm investigating PySide for the correct combination of options to make this resizing fluid. It should not be necessary to have this hack.

2023-04-25 12:35 UTC, dc2917 commented
> Starting to renew this. It looks good, but the process is not that robust. This is what I get after a couple of resizes (in MacOS):
> 
> <img alt="image" width="814" src="https://user-images.githubusercontent.com/6095790/234270506-f2529559-fb8d-49b8-82b1-a1f97cdbd21c.png">
> 
> I'm investigating PySide for the correct combination of options to make this resizing fluid. It should not be necessary to have this hack.

Interesting, that looks like it's ignored (or perhaps overwritten) the minimum size setting.

2023-06-27 10:26 UTC, alexdewar commented
@dc2917 What's happening with this PR? Did we decide not to merge this one and merge @dalonsoa's fix instead? If so, would you mind opening a new PR for that one into `main` please?

2023-06-27 10:58 UTC, dc2917 commented
Sorry @alexdewar this completely slipped my mind. Diego's fix has been merged into this one, I'll remove the custom resize function itself and push now.

2023-07-10 11:08 UTC, alexdewar commented
@dc2917 Does anything else need doing or is this good to merge?

2023-07-10 11:23 UTC, merged