Seneca K107 checksum function
ImperialCollegeLondon/FINESSE pull request #429
Opened 2023-11-22 10:08 UTC by CWestICL

Added a `calculate_crc()` function to the `SenekaK107` class that calculates the checksum from incoming data and compares it with the value at the end of the bytestring for validation. If the values don't match, an error is raised. The package 'crc' has also been added to the `poetry` environment.

Closes #400

2023-11-22 10:10 UTC, CWestICL commented
Opened in draft as the data I have saved to test this function isn't passing the validation. I'm going into the lab this afternoon to test it with some fresh data and to double-check the original C# code the function is based on is functioning correctly.

2024-01-22 19:01 UTC, dc2917 requested changes
Some minor changes but otherwise looks good!

2024-01-23 09:47 UTC, CWestICL commented on finesse/hardware/plugins/temperature/senecak107.py
> +
As it stands without the ignore statement, mypy throws out this error: `error: Incompatible return value type (got "ndarray[Any, Any]", expected "Sequence[Any]")`

2024-01-23 09:50 UTC, dc2917 commented on finesse/hardware/plugins/temperature/senecak107.py
> +
Yeah, exactly. The return type annotation is wrong, it should be `numpy.ndarray`, not `Sequence`.

2024-01-23 09:58 UTC, CWestICL commented on finesse/hardware/plugins/temperature/senecak107.py
> +
Ah right gotcha

2024-01-23 10:03 UTC, CWestICL commented on finesse/hardware/plugins/temperature/senecak107.py
> +
Ok so I now remember why we used `Sequence` before, the `TemperatureMonitorBase` base class is using `Sequence` as the return type for the `get_temperatures()` function, so we get a differnet mypy error when using `numpy.ndarray`: `error: Return type "ndarray[Any, Any]" of "get_temperatures" incompatible with return type "Sequence[Any]" in supertype "TemperatureMonitorBase"`

2024-01-24 10:03 UTC, dc2917 commented on finesse/hardware/plugins/temperature/senecak107.py
> +
Ah okay, yeah that makes sense. In that case, we should follow what the base class is doing and have `get_temperatures()` return a `Sequence`.
`return self.parse_data(data).tolist()` should do the trick.

2024-01-24 15:25 UTC, dc2917 approved these changes

2024-01-24 15:26 UTC, merged