Get mirror immediate position
ImperialCollegeLondon/FINESSE pull request #743
Opened 2024-12-11 18:18 UTC by dc2917

# Description

Fixes #691 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation (non-breaking change that adds or improves the documentation)
- [ ] Optimisation (non-breaking, back-end change that speeds up the code)

## Key checklist

- [ ] Pre-commit hooks run successfully (`pre-commit run -a`)
- [ ] All tests pass (`pytest`)
- [ ] The documentation builds without warnings (`mkdocs build -s`)
- [ ] Check the GUI still works (if relevant)
- [ ] Check the code works with actual hardware (if relevant)
- [ ] Check the `pyinstaller`-built executable works (if relevant)

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests have been added or an issue has been opened to tackle that in the future. (Indicate issue here: # (issue))

2024-12-12 14:19 UTC, alexdewar requested changes
I've made one suggestion about the test, but it otherwise looks good. Thanks for doing this!

I think it's fine to leave `DummyStepperMotor` as it is for now -- let's not make things hard for ourselves.

I've just realised that we also need to update `data_file_writer.py`, because we record whether or not the motor is moving as a column in the CSV file and it currently does this by checking whether the returned angle is `None`. Would you mind fixing this up too?

2024-12-12 14:19 UTC, alexdewar commented on tests/hardware/plugins/stepper_motor/test_st10_controller.py
>      is_moving_mock.return_value = True
We don't actually need to mock `ST10Controller.is_moving` anymore because it's not called by `ST10Controller.step`

2024-12-13 08:51 UTC, dc2917 commented
> I've just realised that we also need to update data_file_writer.py, because we record whether or not the motor is moving as a column in the CSV file and it currently does this by checking whether the returned angle is None. Would you mind fixing this up too?

I've removed that column from the CSV file entirely. I presume that's what we want, since the only way we check for whether the mirror is moving is if it returns `None`, which will never happen.

2024-12-13 09:31 UTC, alexdewar requested changes
The stepper motor classes do have an `is_moving` property that you can use instead. Unfortunately we do need this column -- sorry I wasn't clear :disappointed:

2024-12-13 12:04 UTC, alexdewar approved these changes
LGTM! Thanks for fixing up that extra file :smile:

2024-12-13 12:34 UTC, merged